language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t ashishmahawal/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ashishmahawal/docker-react npm run test